// <auto-generated />
using System;
using LotteryDraw.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LotteryDraw.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220825080024_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LotteryDraw.Domain.Entities.HistoryDraw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DrawTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("FifthNumber")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FirstNumber")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FourthNumber")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SecondNumber")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ThirdNumber")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("DrawHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
